server:
  port: 8080

ms:
  users:
    path: localhost
    port: 8081
  notes:
    path: localhost
    port: 8082

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWT_PUBLIC_KEY_URI:https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com}
          issuer-uri: ${ISSUER_URL:https://securetoken.google.com/notes-app-8c8db}

logging:
  level:
    org:
      springframework:
        security: DEBUG