server:
  port: ${SERVER_PORT:8080}

ms:
  users:
    path: ${USERS_MS_PATH:localhost}
    port: ${USERS_MS_PORT:8081}
  notes:
    path: ${NOTES_MS_PATH:localhost}
    port: ${NOTES_MS_PORT:8082}

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWT_PUBLIC_KEY_URI:https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com}
          issuer-uri: ${ISSUER_URL:https://securetoken.google.com/notes-app-8c8db}